// This file is auto-generated by "script/generate-src.ts"
// please run "npm run generate:src" to update this file.
import * as AOE3 from './aoe3';
import * as CHIBI from './chibi';
import * as CLASSIC from './classic';
import * as CLASSIC_CARDS from './classic-cards';
import * as CLASSIC_CUSTOM_COLORED from './classic-custom-colored';
import * as CLASSIC_LUFEN from './classic-lufen';
import * as DIY2020 from './diy2020';
import * as GUOZHAN from './guozhan';
import * as MOBILE from './mobile';
import * as ROCKMAN from './rockman';
import * as SPCLOUD from './spcloud';
import * as STAR_SP from './star-sp';
import * as XHLSGS from './xhlsgs';
import * as YINHUA from './yinhua';
import * as YLHUGE from './ylhuge';

export { AOE3, CHIBI, CLASSIC, CLASSIC_CARDS, CLASSIC_CUSTOM_COLORED, CLASSIC_LUFEN, DIY2020, GUOZHAN, MOBILE, ROCKMAN, SPCLOUD, STAR_SP, XHLSGS, YINHUA, YLHUGE }

export const CardResources = {
  'AOE3': AOE3,
  'CHIBI': CHIBI,
  'CLASSIC': CLASSIC,
  'CLASSIC_CARDS': CLASSIC_CARDS,
  'CLASSIC_CUSTOM_COLORED': CLASSIC_CUSTOM_COLORED,
  'CLASSIC_LUFEN': CLASSIC_LUFEN,
  'DIY2020': DIY2020,
  'GUOZHAN': GUOZHAN,
  'MOBILE': MOBILE,
  'ROCKMAN': ROCKMAN,
  'SPCLOUD': SPCLOUD,
  'STAR_SP': STAR_SP,
  'XHLSGS': XHLSGS,
  'YINHUA': YINHUA,
  'YLHUGE': YLHUGE,
} as const;

export const CardResourcesKeys = ['AOE3', 'CHIBI', 'CLASSIC', 'CLASSIC_CARDS', 'CLASSIC_CUSTOM_COLORED', 'CLASSIC_LUFEN', 'DIY2020', 'GUOZHAN', 'MOBILE', 'ROCKMAN', 'SPCLOUD', 'STAR_SP', 'XHLSGS', 'YINHUA', 'YLHUGE'] as const;

export const CardResourcesValues = ["aoe3", "chibi", "classic", "classic-cards", "classic-custom-colored", "classic-lufen", "diy2020", "guozhan", "mobile", "rockman", "spcloud", "star-sp", "xhlsgs", "yinhua", "ylhuge"] as const;

export type CardResourcesKeysType = typeof CardResourcesKeys[number];

export type CardResourcesValuesType = typeof CardResourcesValues[number];

export const CardResourcesMap: Record<CardResourcesKeysType, CardResourcesValuesType>= {
  'AOE3': 'aoe3',
  'CHIBI': 'chibi',
  'CLASSIC': 'classic',
  'CLASSIC_CARDS': 'classic-cards',
  'CLASSIC_CUSTOM_COLORED': 'classic-custom-colored',
  'CLASSIC_LUFEN': 'classic-lufen',
  'DIY2020': 'diy2020',
  'GUOZHAN': 'guozhan',
  'MOBILE': 'mobile',
  'ROCKMAN': 'rockman',
  'SPCLOUD': 'spcloud',
  'STAR_SP': 'star-sp',
  'XHLSGS': 'xhlsgs',
  'YINHUA': 'yinhua',
  'YLHUGE': 'ylhuge',
} as const;

export type CardResourcesTypes = typeof CardResources[keyof typeof CardResources];

